@startuml
hide footbox
!theme plain
skinparam backgroundcolor transparent

' Turquoise #668c97
' Orange #F6921E

participant "Notebook\nAE" as AE 
box "CSE & Hosted Resources" #f8f8f8
participant "StreetLight-AE-1\nLight-Container-1" as container1 
participant "StreetLight-AE-2\nLight-Container-2" as container2 
end box

AE -> container1 ++: CREATE <contentInstance>\ncse-in/StreetLight-AE-1/Light-Container-1
AE <- container1 --: Response

@enduml