@startuml
hide footbox
!theme plain
skinparam backgroundcolor transparent

box "Streetlight 1 Notebooks" #f8f8f8
participant "Streetlight-1\nAE" as AE1
participant "Notification\nReceiver" as NS
end box

participant "CSE" as CSE 

box "Streetlight 2" #f8f8f8
participant "Streetlight-2\nAE" as AE2
end box

AE1 -> CSE: CREATE <contentInstance>\ncse-in/StreetLight-AE-2/Light-Container-2
AE1 <- CSE: Response
CSE -> NS: NOTIFY <notification>
CSE <- NS: Response

@enduml