@startuml
hide footbox
!theme plain
skinparam backgroundcolor transparent

participant "Notebook\nAE" as AE 
participant "CSE" as CSE 

AE -> CSE: RETRIEVE <contentInstances>\ncse-in/Notebook-AE/Container\nty=4, child references
CSE --> CSE: Collect\nresources
AE <- CSE: Response

@enduml