@startuml
hide footbox
!theme plain
skinparam backgroundcolor transparent

participant "Notebook\nAE" as AE 
participant "CSE" as CSE 

AE -> CSE: UPDATE <container>\ncse-in/Notebook-AE/Container
AE <- CSE: Response

@enduml