@startuml
hide footbox
!theme plain
skinparam backgroundcolor transparent

participant "Notebook\nAE" as AE 
participant "CSE" as CSE 

AE -> CSE: CREATE [color]\ncse-in/Notebook-AE
AE <- CSE: Response

@enduml